In [243]:
import nltk
import numpy as np
from collections import defaultdict
from scipy import stats

In [244]:
#download tokenizer
path='D:/misc/Projects/Python/NLP/misc'
nltk.download('punkt_tab',download_dir=path)
nltk.download('wordnet',download_dir=path)
nltk.download('omw-1.4',download_dir=path)
nltk.data.path.append(path)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     D:/misc/Projects/Python/NLP/misc...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     D:/misc/Projects/Python/NLP/misc...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     D:/misc/Projects/Python/NLP/misc...
[nltk_data]   Package omw-1.4 is already up-to-date!


## 2)

In [245]:
#read files
with open('prova.txt','r') as f:
    data=f.read().lower().strip()

punctuation=['"','!','.',',',"'",'(',')',';','``',"''",'?','_',':','-']
punctuation=[]

data=data.split('-next-')
data=[ab.strip().split('\n')[:] for ab in data][:]

#remove punctuation from abstracts
for punct in punctuation:
    for i in range(len(data)):
        data[i][2]=data[i][2].replace(punct,'')

#split authors and keywords
for i in range(len(data)):
    data[i][1]=data[i][1].split(',')
    data[i][3]=data[i][3].split(',')
data

[['advancements and challenges of fuel cell integration in electric vehicles: a comprehensive analysis artificial intelligence',
  ['manpreet singh',
   ' manish kumar singla',
   ' murodbek safaraliev',
   ' kulwinder singh',
   ' ismoil odinaev',
   ' amir abdel menaem'],
  'fuel cell technology emerges as a promising green solution, offering mitigation to global warming, air pollution, and energy crises. this eco-friendly approach is witnessing a surge in adoption within the automotive sector, with fuel cell buses, cars, scooters, forklifts, and more, becoming increasingly prevalent. the automobile industry has been rapidly advancing fuel cell technology, inching closer to the commercialization of fuel cell vehicles. as various technical hurdles are surmounted and costs are reduced, fuel cell vehicles are poised to become a competitive force in the automobile market, presenting an excellent solution for environmental sustainability and energy efficiency. this review paper delves int

In [246]:
len(data)

5

In [247]:
#custom dictionary class to conveniently add new items
class inverted_index_dict:
    def __init__(self) -> None:
        self.dict=defaultdict()
        
    def add_item(self,token,doc):
        if self.dict.__contains__(token):
            if doc not in self.dict[token]:
                self.dict[token].append(doc)
        else:
            self.dict[token]=[doc]
    
inverted_index=inverted_index_dict()

for j,ab in enumerate(data):
    for i,kw in enumerate(ab[3]):
        inverted_index.add_item(kw.strip(),j)

inverted_index.dict

defaultdict(None,
            {'fuel cell': [0],
             'hydrogen': [0],
             'electric vehicles': [0],
             'renewable energy': [0],
             'sustainability': [0],
             'chronic kidney disease': [1],
             'acute kidney injury': [1],
             'failed repair': [1],
             'adaptive cell state': [1],
             'maladaptive repair': [1],
             'micro-supercapacitors': [2],
             'laser-induced graphene': [2],
             'fluorinated polyimide': [2],
             'phosphorus doping': [2],
             'artificial intelligence': [3, 4],
             'chatgpt-4': [3],
             'omnie-learning': [3],
             'gemini 1.5': [3],
             'prolarge language model': [3],
             'medical education': [3],
             'ophthalmology': [3],
             'climate change': [4],
             'extreme value theory': [4],
             'flood frequency analysis': [4],
             'flood hazard': [4],
             '

In [248]:
#ordering
kk=list(inverted_index.dict.items())
kk=sorted(kk,key=lambda x: x[0])
kk

[('acute kidney injury', [1]),
 ('adaptive cell state', [1]),
 ('artificial intelligence', [3, 4]),
 ('chatgpt-4', [3]),
 ('chronic kidney disease', [1]),
 ('climate change', [4]),
 ('electric vehicles', [0]),
 ('extreme value theory', [4]),
 ('failed repair', [1]),
 ('flood frequency analysis', [4]),
 ('flood hazard', [4]),
 ('fluorinated polyimide', [2]),
 ('fuel cell', [0]),
 ('gemini 1.5', [3]),
 ('goodness of fit', [4]),
 ('hydrogen', [0]),
 ('hydrological modeling', [4]),
 ('kashmir valley', [4]),
 ('laser-induced graphene', [2]),
 ('maladaptive repair', [1]),
 ('medical education', [3]),
 ('micro-supercapacitors', [2]),
 ('omnie-learning', [3]),
 ('ophthalmology', [3]),
 ('phosphorus doping', [2]),
 ('prolarge language model', [3]),
 ('renewable energy', [0]),
 ('sustainability', [0])]

In [249]:
'''
as suggested by the TA, if we have multiple words as keyword (e.g. artificial intelligence),
we split the keyword as 'artificial' and 'intelligence'
'''
#concatenate keywords
concatenated_keywords=set([word.strip() for i,ab in enumerate(data) for word in ab[3]])
T='artificial intelligence'
output='T: artificial intelligence\n'
#flatten each word in keyword
keywords=[k.split() for k in concatenated_keywords]
keywords=[p for x in keywords for p in x]
keywords=set(keywords)
X=[[k,0] for k in keywords]

for i,kw in enumerate(keywords):
    simil=min(nltk.distance.edit_distance('artificial',kw),nltk.distance.edit_distance('intelligence',kw))
    X[i][1]=simil
    output+=f'{kw}: {simil}\n'
X=sorted(X,key=lambda x: x[0])
print(output)

T: artificial intelligence
micro-supercapacitors: 18
sustainability: 10
energy: 9
laser-induced: 9
analysis: 8
phosphorus: 10
kashmir: 9
ophthalmology: 11
renewable: 9
value: 10
gemini: 8
electric: 9
fuel: 8
hydrological: 8
state: 9
model: 9
disease: 9
fluorinated: 10
climate: 9
hydrogen: 9
theory: 9
maladaptive: 9
doping: 9
omnie-learning: 10
intelligence: 0
flood: 9
kidney: 9
polyimide: 8
valley: 9
adaptive: 8
modeling: 8
artificial: 0
language: 9
medical: 6
goodness: 10
education: 9
acute: 8
fit: 8
1.5: 10
cell: 8
injury: 9
graphene: 9
extreme: 9
chronic: 8
repair: 8
failed: 9
vehicles: 8
change: 10
frequency: 8
hazard: 10
prolarge: 9
chatgpt-4: 10
of: 9



In [250]:
print(X)
len(X),len(keywords)

[['1.5', 10], ['acute', 8], ['adaptive', 8], ['analysis', 8], ['artificial', 0], ['cell', 8], ['change', 10], ['chatgpt-4', 10], ['chronic', 8], ['climate', 9], ['disease', 9], ['doping', 9], ['education', 9], ['electric', 9], ['energy', 9], ['extreme', 9], ['failed', 9], ['fit', 8], ['flood', 9], ['fluorinated', 10], ['frequency', 8], ['fuel', 8], ['gemini', 8], ['goodness', 10], ['graphene', 9], ['hazard', 10], ['hydrogen', 9], ['hydrological', 8], ['injury', 9], ['intelligence', 0], ['kashmir', 9], ['kidney', 9], ['language', 9], ['laser-induced', 9], ['maladaptive', 9], ['medical', 6], ['micro-supercapacitors', 18], ['model', 9], ['modeling', 8], ['of', 9], ['omnie-learning', 10], ['ophthalmology', 11], ['phosphorus', 10], ['polyimide', 8], ['prolarge', 9], ['renewable', 9], ['repair', 8], ['state', 9], ['sustainability', 10], ['theory', 9], ['valley', 9], ['value', 10], ['vehicles', 8]]


(53, 53)

## 3)

In [251]:
Y=[]
concatenated_keywords=set([word.strip() for i,ab in enumerate(data) for word in ab[3]])

split_kk=[[k[0].split(),k[1]] for k in kk]
for kws,ids in split_kk:
    for kw in kws:
        for id in ids:
            simils=[]
            for word in data[id][0].split():
                simils.append(nltk.distance.edit_distance(word,kw))
            simil=min(simils)
            Y.append([kw,id,simil])
#each element: keyword, document it appears in, edit distance with the title of that document

In [252]:
Y=sorted(Y,key=lambda x: x[0])
i=0
new_Y=[]
w=Y[0][0]
distances=[]
while i<len(Y):
    if Y[i][0]!=w:
        new_Y.append([w,min(distances)])
        w=Y[i][0]
        distances=[Y[i][2]]
    else:
        distances.append(Y[i][2])
    i+=1
new_Y.append([w,min(distances)])
new_Y

[['1.5', 0],
 ['acute', 4],
 ['adaptive', 6],
 ['analysis', 0],
 ['artificial', 0],
 ['cell', 0],
 ['change', 4],
 ['chatgpt-4', 0],
 ['chronic', 5],
 ['climate', 6],
 ['disease', 6],
 ['doping', 5],
 ['education', 5],
 ['electric', 0],
 ['energy', 5],
 ['extreme', 5],
 ['failed', 4],
 ['fit', 2],
 ['flood', 0],
 ['fluorinated', 0],
 ['frequency', 0],
 ['fuel', 0],
 ['gemini', 0],
 ['goodness', 6],
 ['graphene', 0],
 ['hazard', 5],
 ['hydrogen', 7],
 ['hydrological', 8],
 ['injury', 2],
 ['intelligence', 0],
 ['kashmir', 4],
 ['kidney', 0],
 ['language', 0],
 ['laser-induced', 6],
 ['maladaptive', 7],
 ['medical', 4],
 ['micro-supercapacitors', 0],
 ['model', 1],
 ['modeling', 6],
 ['of', 0],
 ['omnie-learning', 10],
 ['ophthalmology', 8],
 ['phosphorus', 2],
 ['polyimide', 0],
 ['prolarge', 3],
 ['renewable', 7],
 ['repair', 5],
 ['state', 3],
 ['sustainability', 10],
 ['theory', 3],
 ['valley', 5],
 ['value', 4],
 ['vehicles', 1]]

## 4)

In [253]:
npX=np.array([x[1] for x in X])
npY=np.array([y[1] for y in new_Y])
stats.pearsonr(npX,npY)

PearsonRResult(statistic=0.15189963058878994, pvalue=0.2775708184984361)

## 5)

In [266]:
#get all unique keywords
concatenated_keywords=set([word.strip() for i,ab in enumerate(data) for word in ab[3]])
keywords=[k.split() for k in concatenated_keywords]
keywords=[p for x in keywords for p in x]
keywords=list(set(keywords))
M=np.zeros((len(data),len(keywords)))

for i,kw in enumerate(keywords):
    for j,ab in enumerate(data):
        abstract=data[j][2]
        num=abstract.count(kw)
        M[j,i]=num

M

array([[ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        11.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,
         5.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  4.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         8.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         3.],
       [ 1.,  0.,  3.,  1.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         2.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        10.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         

## 6)

In [268]:
def boolean_matching(query,db=M,kws=keywords):
    qkeys=query.split()
    result=np.ones(len(data))
    for qkey in qkeys:
        i=kws.index(qkey)
        doc_res=db[:,i]
        doc_res[doc_res>0]=1
        result=np.logical_and(result,doc_res)
    return result

query='artificial intelligence'
boolean_matching(query)

array([False, False, False,  True, False])

## 7)

In [282]:
n=len(data)
df=np.zeros(len(keywords))
for i,col in enumerate(M.T):
    df[i]=len(col[col>0])

idf=np.log10(n/df)

tfidf_M=M*idf

def tfidf_matching(query,tfidf=tfidf_M,kws=keywords,df=df):
    qkeys=query.split()
    results=np.zeros(len(data))
    for qkey in qkeys:
        if qkey not in keywords:
            continue
        i=kws.index(qkey)
        for col in M:
            results+=col[i]*np.log10(n/df[i])
    return results
        
        


query='artificial intelligence'
tfidf_matching(query)

C:\Users\emanu\AppData\Local\Temp\ipykernel_9968\3859817929.py:6: RuntimeWarning: divide by zero encountered in divide
  idf=np.log10(n/df)
C:\Users\emanu\AppData\Local\Temp\ipykernel_9968\3859817929.py:8: RuntimeWarning: invalid value encountered in multiply
  tfidf_M=M*idf


array([1.39794001, 1.39794001, 1.39794001, 1.39794001, 1.39794001])

In [280]:
df

array([1., 1., 2., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 2., 1.,
       1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0.,
       1., 0., 0., 1., 0., 3., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 5.])

In [278]:
for i in M.T:
    print(len(i[i>0]))
    print(i)
    break

1
[0. 0. 1. 0. 0.]
